Repository clue/reactphp-http-proxy, pull requests merged in 2020-06, with the labels that each got.

#31 Clean up test suite, add .gitattributes to exclude dev files from exports and run tests on PHP 7.4 and simplify test matrix
  .gitattributes
  .travis.yml
  composer.json
  tests/AbstractTestCase.php
  tests/FunctionalTest.php
  tests/ProxyConnectorTest.php
Labels: maintenance

#32 Added name to testsuite to avoid warning
  phpunit.xml.dist
Labels: easy pick, maintenance

#33 Avoid PHP warnings due to lack of args in exception trace on PHP 7.4
  src/ProxyConnector.php
Labels: bug, easy pick

#34 Run test on PHPUnit 9
  composer.json
  tests/AbstractTestCase.php
  tests/FunctionalTest.php
  tests/ProxyConnectorTest.php
Labels: maintenance
