Repository clue/reactphp-http-proxy, pull requests merged in 2022-06, with the labels that each got.

#46 Fix legacy HHVM build by downgrading Composer
  .github/workflows/ci.yml
  README.md
Labels: maintenance

#45 Fix invalid references in exception stack trace
  src/ProxyConnector.php
  tests/ProxyConnectorTest.php
Labels: bug

#47 Support PHP 8.1
  .github/workflows/ci.yml
  phpunit.xml.dist
Labels: maintenance, new feature
